-------------------------------------------------------------------------------
--- Lua utility functions
-- Hex math courtesy of Reb Blob Games
-- @author bonkersbgg on BoardGameGeek.com
-------------------------------------------------------------------------------

local CrLua = CrLua or {}
CrLua.Hex = assert(not CrLua.Hex) and {}

function CrLua.Hex.layout()
end

-------------------------------------------------------------------------------
--- Get hex from a position.
-- Use strings to represent hexes so when used as table keys collide for same.
-- @param position table : {x,y,z} keys.
-- @return hex string : string representation of the hex.
-------------------------------------------------------------------------------
function CrLua.Hex.hex(position)
end

function CrLua.Hex.neighbors(hex)
end
