--- Announces purged objects.
-- @author Darrell (copied from Deleted Items)
-- @author Jabberwocky
--

function onObjectEnterContainer(bag, enterObject)
    if bag == self then
        printToAll('PURGING ' .. enterObject.getName(), 'Yellow')
    end
end

function onObjectLeaveContainer(bag, leaveObject)
    if bag == self then
        printToAll("unPURGING " .. leaveObject.getName(), 'Yellow')
    end
end
